services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=plot'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=plot'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - "${PLOT_POSTGRES_PORT:-5433}:5432"
